spring.application.name=developer-portfolio-analyzer

# PostgreSQL Database (Render)
spring.datasource.url=jdbc:postgresql://dpg-d6qit5q4d50c73be3qn0-a.oregon-postgres.render.com:5432/portfolio_db_1tyb
spring.datasource.username=mahek
spring.datasource.password=eUJ04ixJCXBz6JU2QltWe7GiUmOVipin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=9090

# GitHub API Token (optional)
# Get your token from: https://github.com/settings/tokens
# Replace YOUR_TOKEN_HERE with your actual GitHub token
github.api.token=YOUR_TOKEN_HERE