spring.application.name=developer-portfolio-analyzer

spring.datasource.url=jdbc:mysql://localhost:3306/portfolio_db
spring.datasource.username=root
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.port=9090

# GitHub API Token (optional, add your token here for higher rate limits)
# Get your token from: https://github.com/settings/tokens
github.api.token=